swagger: '2.0'
info:
  title: Vandelay Industries API - DRAFT
  description: >-
    [Vandelay Industries](http://www.urbandictionary.com/define.php?term=Vandelay) is a
    vertically integrated chemical manufaturing, import/export, and sales
    enterprise headquartered in the Upper West Side, NYC. It was founded by Art
    Vandely in 1990.


    It is known both for the quality of its product as well as its aggressive
    salesperson recruiting program.


    The Vandelay Industries API platform, documented here, represents a unified
    view of its ERP and CRM systems for use by both internal applications and
    3rd-party strategic partner system integrations.


  version: 0.0.1-alpha
  termsOfService: 'http://vandelay.apivista.com/terms/'

host: vandelay.apivista.com
schemes:
  - https
basePath: /v0-alpha
paths:
  /factories:
    get:
      tags:
        - factories
      summary: List factories in the ERP system
      description: >-
        The factory is an important top-level object for tracking both
        manufacturing activities as well as supply chain & order fulfillment,
        underpinning Vandelays import/export business.
      operationId: getFactories
      security:
        - vandalay_auth:
            - 'read:factories'

    post:
      tags:
        - factories
      summary: Create a factory in the ERP system
      description: >-
        The factory is an important top-level object for tracking both
        manufacturing activities as well as supply chain & order fulfillment,
        underpinning Vandelays import/export business.
      operationId: createFactory
      security:
        - vandalay_auth:
            - 'read:factories'
            - 'write:factories'
  '/factories/{factoryId}':
    get:
      tags:
        - factories
      summary: Get a factory in the ERP system
      description: >-
        The factory is an important top-level object for tracking both
        manufacturing activities as well as supply chain & order fulfillment,
        underpinning Vandelays import/export business.
      operationId: getFactory
      security:
        - vandalay_auth:
            - 'read:factories'
            - 'write:factories'
    patch:
      tags:
        - factories
      summary: Update a factory in the ERP system
      description: >-
        The factory is an important top-level object for tracking both
        manufacturing activities as well as supply chain & order fulfillment,
        underpinning Vandelays import/export business.
      operationId: updateFactory
      security:
        - vandalay_auth:
            - 'read:factories'
            - 'write:factories'
    delete:
      tags:
        - factories
      summary: Delete a factory in the ERP system
      description: >-
        The factory is an important top-level object for tracking both
        manufacturing activities as well as supply chain & order fulfillment,
        underpinning Vandelays import/export business.
      operationId: deleteFactoriey
      security:
        - vandalay_auth:
            - 'read:factories'
            - 'write:factories'

  '/factories/{factoryId}/machines':
    get:
      tags:
        - factories
      summary: List machines at a given factory
      description: >-
        The factory is an important top-level object for tracking both
        manufacturing activities as well as supply chain & order fulfillment,
        underpinning Vandelays import/export business.
      operationId: getMachines
      security:
        - vandalay_auth:
            - 'read:factories'
            - 'read:machines'
    post:
      tags:
        - factories
      summary: Records the addition of a machine at a given factory
      operationId: createMachineForFactory
      security:
        - vandalay_auth:
            - 'read:factories'
            - 'read:machines'
            - 'write:machines'

  '/factories/{factoryId}/machines/{machineId}':
    get:
      tags:
        - factories
      summary: Returns a machine at a given factory
      operationId: getMachineByIdByFactory
      security:
        - vandalay_auth:
            - 'read:factories'
            - 'read:machines'

    patch:
      tags:
        - factories
      summary: Updates a machine at a given factory
      operationId: updateMachineByIdByFactory
      security:
        - vandalay_auth:
            - 'read:factories'
            - 'read:machines'
            - 'write:machines'

    delete:
      tags:
        - factories
      summary: Deletes a machine at a given factory
      operationId: deleteMachineByIdByFactory
      security:
        - vandalay_auth:
            - 'read:factories'
            - 'read:machines'
            - 'write:machines'

  /warehouses:
    get:
      tags:
        - warehouses
      summary: List warehouses in the ERP system
      description: >-
        The warehouse is an important top-level object for tracking both inbound
        material and outbound product.
      operationId: getWarehouses
      security:
        - vandalay_auth:
            - 'read:warehouses'

    post:
      tags:
        - warehouses
      summary: List warehouses in the ERP system
      description: >-
        The warehouse is an important top-level object for tracking both inbound
        material and outbound product.
      operationId: createWarehouse
      security:
        - vandalay_auth:
            - 'read:warehouses'
            - 'write:warehouses'

  '/warehouses/{warehouseId}':
    get:
      tags:
        - warehouses
      summary: Get a warehouse in the ERP system
      description: >-
        The warehouse is an important top-level object for tracking both inbound
        material and outbound product.
      operationId: getWarehouseById
      security:
        - vandalay_auth:
            - 'read:warehouses'

    patch:
      tags:
        - warehouses
      summary: Update a warehouse in the ERP system
      description: >-
        The warehouse is an important top-level object for tracking both inbound
        material and outbound product.
      operationId: updateWarehouseById
      security:
        - vandalay_auth:
            - 'read:warehouses'
            - 'write:warehouses'

    delete:
      tags:
        - warehouses
      summary: Delete a warehouse in the ERP system
      description: >-
        The warehouse is an important top-level object for tracking both inbound
        material and outbound product.
      operationId: deleteWarehouseById
      security:
        - vandalay_auth:
            - 'read:warehouses'
            - 'write:warehouses'

  '/warehouses/{warehouseId}/inventory':
    get:
      tags:
        - warehouses
      summary: Return an array containing inventory for a single warehouse
      description: Currently an unpaged inventory list
      operationId: getInventoryByWarehouseId
      security:
        - vandalay_auth:
            - 'read:warehouses'
            - 'read:inventory'

    post:
      tags:
        - warehouses
      summary: Records the addition of inventory to a warehouse
      operationId: addItem
      security:
        - vandalay_auth:
            - 'read:warehouses'
            - 'read:inventory'
            - 'write:inventory'

  '/warehouses/{warehouseId}/inventory/{inventoryId}':
    get:
      tags:
        - warehouses
      summary: Returns a single inventory for a single warehouse
      description: Currently an unpaged inventory list
      operationId: getInventoryItemByWarehouseId
      security:
        - vandalay_auth:
            - 'read:warehouses'
            - 'read:inventory'

    patch:
      tags:
        - warehouses
      summary: Updates an inventory item in a warehouse
      operationId: updateItem
      security:
        - vandalay_auth:
            - 'read:warehouses'
            - 'read:inventory'
            - 'write:inventory'

    delete:
      tags:
        - warehouses
      summary: Deletes an inventory item in a warehouse
      operationId: deleteWarehouseItem
      security:
        - vandalay_auth:
            - 'read:warehouses'
            - 'read:inventory'
            - 'write:inventory'

securityDefinitions:
  vandalay_auth:
    type: oauth2
    authorizationUrl: 'https://vandelay.apivista.com/oauth/authorize'
    flow: implicit
    scopes:
      'write:factories': modify factories
      'read:factories': read factories
      'write:machines': modify machines
      'read:machines': read machines
      'write:warehouses': modify warehouses
      'read:warehouses': read warehouses
      'write:inventory': modify inventory
      'read:inventory': read inventory
